/** ARCHITECTURE SOURCE OF TRUTH — services 13 to 24. See services.part1.mjs for the field DSL. */

export const SERVICES_PART_2 = [
  // 13 -----------------------------------------------------------------
  {
    id: 'education',
    name: 'Adaptive Education OS',
    ministry: 'Education',
    summary:
      'A learning twin per learner cohort, schools that report their own condition, one knowledge graph.',
    mission:
      'Adapt what is taught to what the country is measurably about to need, and notice a failing school building before it is a headline.',
    modules: [
      {
        id: 'student-learning-twin',
        name: 'Student Learning Twin',
        purpose: 'Cohort-level mastery and progression, never a named pupil.',
      },
      {
        id: 'smart-school-iot',
        name: 'Smart School IoT',
        purpose: 'Air quality, occupancy and building condition per school.',
      },
      {
        id: 'national-knowledge-graph',
        name: 'National Knowledge Graph',
        purpose: 'Concepts, prerequisites and programme coverage.',
      },
    ],
    owns: ['SchoolRef', 'EducationProgramRef', 'LearnerCohortRef'],
    entity: {
      collection: 'schools',
      label: 'School',
      fields: {
        level: 'enum:primary|secondary|vocational|university',
        governorate: 'gov',
        location: 'geo',
        pupils: 'int',
        teachers: 'int',
        buildingCondition: 'unit',
        airQualityIndex: 'number',
        digitalReadiness: 'unit',
        dropoutRate: 'unit',
      },
      seed: 42,
      twin: {
        type: 'school',
        labelField: 'level',
        stateFields: ['buildingCondition', 'dropoutRate', 'digitalReadiness'],
      },
    },
    events: [
      {
        type: 'education.learning-progress.updated.v1',
        summary: 'Cohort mastery moved for a domain.',
        fields: {
          cohortId: 'string',
          governorate: 'gov',
          domain: 'string',
          masteryIndex: 'unit',
          pupils: 'int',
          updatedAt: 'date',
        },
      },
      {
        type: 'education.program.updated.v1',
        summary: 'A programme was created or adapted, usually against a detected skill gap.',
        fields: {
          programId: 'string',
          title: 'string',
          level: 'string',
          discipline: 'string',
          governorate: 'gov',
          reason: 'text',
          updatedAt: 'date',
        },
      },
      {
        type: 'education.school-condition.updated.v1',
        summary: 'Building or environmental condition at a school changed.',
        fields: {
          schoolId: 'string',
          governorate: 'gov',
          buildingCondition: 'unit',
          airQualityIndex: 'number',
          pupils: 'int',
          observedAt: 'date',
        },
      },
    ],
    apis: [
      { archetype: 'health' },
      { archetype: 'list', module: 'smart-school-iot' },
      { archetype: 'get', module: 'smart-school-iot' },
      { archetype: 'create', module: 'smart-school-iot' },
      {
        archetype: 'ai',
        method: 'POST',
        path: '/programs/adapt',
        module: 'national-knowledge-graph',
        summary: 'Propose a programme adaptation against a national need.',
        input: { need: 'text', level: 'string?', governorate: 'gov?' },
        output: {
          programId: 'string',
          title: 'string',
          level: 'string',
          discipline: 'string',
          governorate: 'gov',
          reason: 'text',
          updatedAt: 'date',
        },
        publishes: 'education.program.updated.v1',
      },
      {
        archetype: 'analytics',
        method: 'GET',
        path: '/schools/condition',
        module: 'smart-school-iot',
        summary: 'School condition by governorate.',
        groupBy: 'governorate',
        publishes: 'education.school-condition.updated.v1',
      },
      { archetype: 'signals' },
      { archetype: 'twins' },
    ],
    ai: ['learning path adaptation', 'dropout risk detection', 'knowledge graph querying'],
    iot: ['air quality', 'occupancy', 'temperature', 'structural strain'],
    twin: ['school twin', 'learner cohort twin'],
  },

  // 14 -----------------------------------------------------------------
  {
    id: 'research',
    name: 'Tunisia Research Brain',
    ministry: 'Higher Education & Research',
    summary: 'National research as an addressable capability, and a path from result to deployment.',
    mission:
      'Connect what laboratories can already do to what ministries are currently blocked on — the gap between the two is where most public value is lost.',
    modules: [
      {
        id: 'national-research-brain',
        name: 'National Research Brain',
        purpose: 'Projects, disciplines, maturity, findings.',
      },
      {
        id: 'living-lab-tunisia',
        name: 'Living Lab Tunisia',
        purpose: 'Real-territory pilots with instrumented outcomes.',
      },
      {
        id: 'ai-innovation-transfer-engine',
        name: 'AI Innovation Transfer Engine',
        purpose: 'Matches a research result to the ministry that needs it.',
      },
    ],
    owns: ['ResearchProjectRef', 'PatentRef', 'LivingLabRef'],
    entity: {
      collection: 'projects',
      label: 'Research project',
      fields: {
        discipline: 'enum:water|energy|health|agronomy|materials|computing|climate|social|marine',
        institution: 'string',
        governorate: 'gov',
        status: 'enum:proposed|running|completed|transferred',
        trl: 'int',
        budgetTnd: 'number',
        keywords: 'string[]',
      },
      seed: 38,
      twin: { type: 'process', labelField: 'discipline', stateFields: ['status', 'trl'] },
    },
    events: [
      {
        type: 'research.project.published.v1',
        summary: 'A research project was registered or updated.',
        fields: {
          projectId: 'string',
          title: 'string',
          discipline: 'string',
          governorate: 'gov',
          trl: 'int',
          publishedAt: 'date',
        },
      },
      {
        type: 'research.finding.released.v1',
        summary: 'A usable result was released.',
        fields: {
          findingId: 'string',
          projectId: 'string',
          discipline: 'string',
          summary: 'text',
          applicableTo: 'string[]',
          releasedAt: 'date',
        },
      },
      {
        type: 'research.transfer.matched.v1',
        summary: 'A result was matched to a ministry need.',
        fields: {
          transferId: 'string',
          findingId: 'string',
          targetService: 'string',
          need: 'text',
          readiness: 'unit',
          matchedAt: 'date',
        },
      },
    ],
    apis: [
      { archetype: 'health' },
      { archetype: 'list', module: 'national-research-brain' },
      { archetype: 'get', module: 'national-research-brain' },
      { archetype: 'create', module: 'national-research-brain', publishes: 'research.project.published.v1' },
      {
        archetype: 'ai',
        method: 'POST',
        path: '/transfer/match',
        module: 'ai-innovation-transfer-engine',
        summary: 'Find the research result that answers a stated ministry need.',
        input: { need: 'text', targetService: 'string?' },
        output: {
          transferId: 'string',
          findingId: 'string',
          targetService: 'string',
          need: 'text',
          readiness: 'unit',
          matchedAt: 'date',
        },
        publishes: 'research.transfer.matched.v1',
      },
      {
        archetype: 'analytics',
        method: 'GET',
        path: '/capability',
        module: 'living-lab-tunisia',
        summary: 'Research capability by discipline.',
        groupBy: 'discipline',
      },
      { archetype: 'signals' },
      { archetype: 'twins' },
    ],
    ai: ['RAG over publications', 'need-to-capability matching', 'maturity scoring'],
    iot: ['living lab instrumentation'],
    twin: ['project twin', 'living lab twin'],
  },

  // 15 -----------------------------------------------------------------
  {
    id: 'talent',
    name: 'National Talent Intelligence Network',
    ministry: 'Youth & Sports',
    summary: 'Athlete development, facility usage and youth opportunity as one pipeline.',
    mission:
      'Find talent where the facilities and the data already are, and stop losing athletes to injuries and gaps nobody was watching.',
    modules: [
      {
        id: 'athlete-digital-twin',
        name: 'Athlete Digital Twin',
        purpose: 'Load, performance and injury risk from wearable signals.',
      },
      {
        id: 'smart-sports-infrastructure-grid',
        name: 'Smart Sports Infrastructure Grid',
        purpose: 'Facility usage, condition and energy.',
      },
      {
        id: 'youth-opportunity-ai',
        name: 'Youth Opportunity AI',
        purpose: 'Connects young people to missions, training and clubs.',
      },
    ],
    owns: ['AthleteCohortRef', 'SportsFacilityRef'],
    entity: {
      collection: 'facilities',
      label: 'Sports facility',
      fields: {
        facilityType: 'enum:stadium|gymnasium|pool|athletics-track|training-centre|youth-club',
        governorate: 'gov',
        location: 'geo',
        capacity: 'int',
        weeklyUsers: 'int',
        condition: 'unit',
        energyKwhMonth: 'number',
        disciplines: 'string[]',
      },
      seed: 30,
      twin: { type: 'facility', labelField: 'facilityType', stateFields: ['condition', 'weeklyUsers'] },
    },
    events: [
      {
        type: 'talent.performance.updated.v1',
        summary: 'Aggregate performance for an athlete cohort.',
        fields: {
          cohortId: 'string',
          discipline: 'string',
          governorate: 'gov',
          performanceIndex: 'unit',
          athletes: 'int',
          updatedAt: 'date',
        },
      },
      {
        type: 'talent.facility-usage.updated.v1',
        summary: 'Usage and condition at a sports facility.',
        fields: {
          facilityId: 'string',
          governorate: 'gov',
          weeklyUsers: 'int',
          condition: 'unit',
          energyKwhMonth: 'number',
          observedAt: 'date',
        },
      },
      {
        type: 'talent.injury-risk.flagged.v1',
        summary: 'Training load suggests elevated injury risk for a cohort.',
        fields: {
          riskId: 'string',
          cohortId: 'string',
          discipline: 'string',
          riskScore: 'unit',
          drivers: 'string[]',
          flaggedAt: 'date',
        },
      },
    ],
    apis: [
      { archetype: 'health' },
      { archetype: 'list', module: 'smart-sports-infrastructure-grid' },
      { archetype: 'get', module: 'smart-sports-infrastructure-grid' },
      { archetype: 'create', module: 'smart-sports-infrastructure-grid' },
      {
        archetype: 'ai',
        method: 'POST',
        path: '/talent/scout',
        module: 'athlete-digital-twin',
        summary: 'Assess a cohort load profile and flag injury risk.',
        input: { cohortId: 'string', discipline: 'string?' },
        output: {
          riskId: 'string',
          cohortId: 'string',
          discipline: 'string',
          riskScore: 'unit',
          drivers: 'string[]',
          flaggedAt: 'date',
        },
        publishes: 'talent.injury-risk.flagged.v1',
      },
      {
        archetype: 'analytics',
        method: 'GET',
        path: '/facilities/usage',
        module: 'smart-sports-infrastructure-grid',
        summary: 'Facility usage by governorate.',
        groupBy: 'governorate',
        publishes: 'talent.facility-usage.updated.v1',
      },
      { archetype: 'signals' },
      { archetype: 'twins' },
    ],
    ai: ['injury risk from load', 'talent identification', 'facility allocation'],
    iot: ['wearable heart rate', 'occupancy', 'energy load', 'temperature'],
    twin: ['athlete cohort twin', 'facility twin'],
  },

  // 16 -----------------------------------------------------------------
  {
    id: 'religious-heritage',
    name: 'Smart Religious Heritage Network',
    ministry: 'Religious Affairs',
    summary:
      'Sites that report their own condition, buildings that manage their own energy, knowledge that is sourced.',
    mission:
      'Protect fragile places with sensors instead of inspections, and answer questions about heritage from documented sources only.',
    modules: [
      {
        id: 'smart-heritage-sensor-network',
        name: 'Smart Heritage Sensor Network',
        purpose: 'Humidity, strain and vibration on fragile fabric.',
      },
      {
        id: 'smart-building-energy-system',
        name: 'Smart Building / Energy System',
        purpose: 'Consumption and comfort in places of worship.',
      },
      {
        id: 'trusted-knowledge-graph',
        name: 'Trusted Knowledge Graph',
        purpose: 'Sourced, verifiable knowledge — never generated assertion.',
      },
    ],
    owns: ['HeritageSiteRef', 'ManuscriptRef'],
    entity: {
      collection: 'sites',
      label: 'Heritage site',
      fields: {
        siteType: 'enum:mosque|zaouia|madrasa|library|cemetery|shrine',
        governorate: 'gov',
        location: 'geo',
        builtCentury: 'int',
        conditionIndex: 'unit',
        humidityPct: 'number',
        vibrationMmS: 'number',
        energyKwhMonth: 'number',
        visitorsWeek: 'int',
      },
      seed: 28,
      twin: { type: 'heritage-site', labelField: 'siteType', stateFields: ['conditionIndex', 'humidityPct'] },
    },
    events: [
      {
        type: 'heritage.site-condition.updated.v1',
        summary: 'Condition of a heritage site changed.',
        fields: {
          siteId: 'string',
          governorate: 'gov',
          conditionIndex: 'unit',
          humidityPct: 'number',
          vibrationMmS: 'number',
          observedAt: 'date',
        },
      },
      {
        type: 'heritage.energy-usage.updated.v1',
        summary: 'Energy consumption at a site.',
        fields: {
          siteId: 'string',
          governorate: 'gov',
          energyKwhMonth: 'number',
          renewableShare: 'unit',
          observedAt: 'date',
        },
      },
      {
        type: 'heritage.knowledge.published.v1',
        summary: 'A sourced knowledge entry was published.',
        fields: {
          entryId: 'string',
          title: 'string',
          sourceCount: 'int',
          domain: 'string',
          publishedAt: 'date',
        },
      },
    ],
    apis: [
      { archetype: 'health' },
      { archetype: 'list', module: 'smart-heritage-sensor-network' },
      { archetype: 'get', module: 'smart-heritage-sensor-network' },
      { archetype: 'create', module: 'smart-heritage-sensor-network' },
      {
        archetype: 'ai',
        method: 'POST',
        path: '/knowledge/ask',
        module: 'trusted-knowledge-graph',
        summary: 'Answer only from registered sources, and say when there are none.',
        input: { question: 'text' },
        output: { answer: 'text', sources: 'string[]', sourceCount: 'int', confidence: 'unit' },
      },
      {
        archetype: 'analytics',
        method: 'GET',
        path: '/sites/condition',
        module: 'smart-heritage-sensor-network',
        summary: 'Site condition by governorate.',
        groupBy: 'governorate',
        publishes: 'heritage.site-condition.updated.v1',
      },
      { archetype: 'signals' },
      { archetype: 'twins' },
    ],
    ai: ['sourced RAG with refusal', 'degradation forecasting', 'energy optimisation'],
    iot: ['humidity', 'vibration', 'structural strain', 'occupancy', 'energy load'],
    twin: ['site twin', 'building energy twin'],
  },

  // 17 -----------------------------------------------------------------
  {
    id: 'digital-nervous-system',
    name: 'Tunisia Digital Nervous System',
    ministry: 'Digital Economy & Communication Technologies',
    summary: 'The backbone: sensor fabric, identity, service registry and the event bus itself.',
    mission:
      'Be the layer nobody thinks about because it never fails: every sensor observation in the country enters here and reaches whichever ministries care, without any of them knowing the others exist.',
    modules: [
      {
        id: 'tunisia-edge-ai-mesh',
        name: 'Tunisia Edge AI Mesh',
        purpose: 'Edge node health and locally-processed inference.',
      },
      {
        id: 'sovereign-iot-fabric',
        name: 'Sovereign IoT Fabric',
        purpose: 'Sensor registry and the single national ingest endpoint.',
      },
      {
        id: 'national-digital-identity-event-bus',
        name: 'National Digital Identity + Event Bus',
        purpose: 'Service registry, event catalogue, pseudonymous identity.',
      },
    ],
    owns: ['SensorRef', 'SensorObservation', 'EdgeNodeRef', 'EventCatalog'],
    entity: {
      collection: 'sensors',
      label: 'Sensor',
      fields: {
        sensorKind: 'string',
        governorate: 'gov',
        location: 'geo',
        unit: 'string',
        mode: 'enum:simulated|physical',
        lastValue: 'number',
        healthy: 'bool',
      },
      seed: 0,
      twin: { type: 'network', labelField: 'sensorKind', stateFields: ['lastValue', 'healthy'] },
    },
    events: [
      {
        type: 'iot.sensor.observation.v1',
        summary:
          'One sensor observation. The highest-volume event on the platform; ten ministries consume it.',
        fields: {
          observationId: 'string',
          sensorId: 'string',
          sensorKind: 'string',
          value: 'number',
          unit: 'string',
          location: 'geo',
          governorate: 'gov',
          quality: 'enum:good|degraded|suspect',
          observedAt: 'date',
        },
      },
      {
        type: 'dns.sensor.registered.v1',
        summary: 'A new sensor joined the national fabric.',
        fields: {
          sensorId: 'string',
          sensorKind: 'string',
          governorate: 'gov',
          mode: 'enum:simulated|physical',
          ownerService: 'string',
          registeredAt: 'date',
        },
      },
      {
        type: 'dns.edge-node.status.v1',
        summary: 'Edge node reachability and local inference load.',
        fields: {
          nodeId: 'string',
          governorate: 'gov',
          online: 'bool',
          inferenceLoad: 'unit',
          sensorsAttached: 'int',
          observedAt: 'date',
        },
      },
      {
        type: 'dns.identity.verified.v1',
        summary: 'A pseudonymous identity assertion was verified.',
        fields: {
          assertionId: 'string',
          subjectPseudonym: 'string',
          method: 'enum:qr|nfc|otp|federated',
          service: 'string',
          verifiedAt: 'date',
        },
      },
    ],
    apis: [
      { archetype: 'health' },
      { archetype: 'list', module: 'sovereign-iot-fabric' },
      { archetype: 'get', module: 'sovereign-iot-fabric' },
      {
        archetype: 'ingest',
        method: 'POST',
        path: '/sensors/observations',
        module: 'sovereign-iot-fabric',
        summary: 'The national sensor ingest endpoint. Real devices and the simulator both POST here.',
        publishes: 'iot.sensor.observation.v1',
      },
      {
        archetype: 'registry',
        method: 'GET',
        path: '/registry/services',
        module: 'national-digital-identity-event-bus',
        summary: 'Every running ministry service and its routes.',
      },
      {
        archetype: 'catalog',
        method: 'GET',
        path: '/registry/events',
        module: 'national-digital-identity-event-bus',
        summary: 'The full event catalogue with owners and subscribers.',
      },
      {
        archetype: 'analytics',
        method: 'GET',
        path: '/sensors/coverage',
        module: 'tunisia-edge-ai-mesh',
        summary: 'Sensor coverage by governorate.',
        groupBy: 'governorate',
      },
      { archetype: 'signals' },
      { archetype: 'twins' },
    ],
    ai: ['edge inference routing', 'sensor fault detection'],
    iot: ['all 16 sensor kinds — this service owns the fabric'],
    twin: ['sensor network twin', 'edge node twin'],
  },

  // 18 -----------------------------------------------------------------
  {
    id: 'mobility-logistics',
    name: 'Autonomous Mobility & Logistics Grid',
    ministry: 'Transport',
    summary: 'Where people and goods are moving, and the nearest vehicle that can be sent.',
    mission:
      'Answer one question faster than anyone else in the country: what is the closest available resource, and how long until it arrives.',
    modules: [
      {
        id: 'national-mobility-digital-twin',
        name: 'National Mobility Digital Twin',
        purpose: 'Flows, congestion and demand by corridor.',
      },
      {
        id: 'v2x-smart-road-grid',
        name: 'V2X Smart Road Grid',
        purpose: 'Road-side signals and vehicle-to-infrastructure messages.',
      },
      {
        id: 'autonomous-logistics-brain',
        name: 'Autonomous Logistics Brain',
        purpose: 'Freight planning and resource dispatch.',
      },
    ],
    owns: ['TransportResourceRef', 'RouteRef', 'FreightOrderRef', 'MobilityFlow'],
    entity: {
      collection: 'resources',
      label: 'Transport resource',
      fields: {
        resourceType: 'enum:ambulance|bus|truck|water-tanker|drone|boat|rail-unit',
        governorate: 'gov',
        location: 'geo',
        status: 'enum:available|engaged|maintenance|offline',
        capacity: 'number',
        operator: 'string',
        etaMinutes: 'int',
      },
      seed: 60,
      twin: { type: 'vehicle', labelField: 'resourceType', stateFields: ['status', 'etaMinutes'] },
    },
    events: [
      {
        type: 'transport.mobility-demand.updated.v1',
        summary: 'Demand and congestion on a corridor.',
        fields: {
          corridorId: 'string',
          governorate: 'gov',
          demandIndex: 'unit',
          congestionIndex: 'unit',
          mode: 'string',
          observedAt: 'date',
        },
      },
      {
        type: 'transport.resource.dispatched.v1',
        summary: 'A resource was assigned to a request from another ministry.',
        fields: {
          dispatchId: 'string',
          resourceId: 'string',
          resourceType: 'string',
          requestedBy: 'string',
          destination: 'geo',
          etaMinutes: 'int',
          dispatchedAt: 'date',
        },
      },
      {
        type: 'transport.congestion.detected.v1',
        summary: 'Congestion crossed a threshold on a corridor.',
        fields: {
          corridorId: 'string',
          governorate: 'gov',
          congestionIndex: 'unit',
          cause: 'string',
          detectedAt: 'date',
        },
      },
      {
        type: 'logistics.freight.updated.v1',
        summary: 'A freight movement changed state.',
        fields: {
          orderId: 'string',
          originGovernorate: 'gov',
          destinationGovernorate: 'gov',
          tonnes: 'number',
          status: 'enum:planned|loading|moving|delivered|blocked',
          updatedAt: 'date',
        },
      },
    ],
    apis: [
      { archetype: 'health' },
      { archetype: 'list', module: 'national-mobility-digital-twin' },
      { archetype: 'get', module: 'national-mobility-digital-twin' },
      {
        archetype: 'nearest',
        method: 'GET',
        path: '/resources/nearest',
        module: 'autonomous-logistics-brain',
        summary:
          'The closest available resource to a point. Health, Emergency and Resilience all depend on this.',
      },
      {
        archetype: 'dispatch',
        method: 'POST',
        path: '/dispatch',
        module: 'autonomous-logistics-brain',
        summary: 'Assign the closest available resource to a request and broadcast the assignment.',
        publishes: 'transport.resource.dispatched.v1',
      },
      {
        archetype: 'analytics',
        method: 'GET',
        path: '/flows',
        module: 'national-mobility-digital-twin',
        summary: 'Mobility demand by governorate.',
        groupBy: 'governorate',
        publishes: 'transport.mobility-demand.updated.v1',
      },
      { archetype: 'signals' },
      { archetype: 'twins' },
    ],
    ai: ['demand forecasting', 'dispatch optimisation', 'congestion cause attribution'],
    iot: ['traffic flow', 'GPS position', 'air quality', 'noise'],
    twin: ['corridor twin', 'vehicle twin'],
  },

  // 19 -----------------------------------------------------------------
  {
    id: 'infrastructure',
    name: 'Smart Infrastructure OS',
    ministry: 'Equipment & Housing',
    summary: 'Asset health, maintenance before failure, and housing that runs itself.',
    mission:
      'Replace inspection cycles with condition: every bridge, network and building carries a health score other ministries can plan against.',
    modules: [
      {
        id: 'national-infrastructure-digital-twin',
        name: 'National Infrastructure Digital Twin',
        purpose: 'Health per asset, continuously.',
      },
      {
        id: 'predictive-infrastructure-maintenance',
        name: 'Predictive Infrastructure Maintenance',
        purpose: 'Failure prediction and work orders.',
      },
      {
        id: 'autonomous-smart-housing',
        name: 'Autonomous Smart Housing',
        purpose: 'Public housing comfort, energy and water.',
      },
    ],
    owns: ['InfrastructureAssetRef', 'MaintenanceOrderRef', 'HousingUnitRef'],
    entity: {
      collection: 'assets',
      label: 'Infrastructure asset',
      fields: {
        assetType: 'enum:road|bridge|water-network|sewage|power-line|port|rail|building|dam|telecom-site',
        governorate: 'gov',
        location: 'geo',
        commissionedYear: 'int',
        healthIndex: 'unit',
        criticality: 'enum:low|medium|high|vital',
        lastInspection: 'date',
        strainMicro: 'number',
      },
      seed: 46,
      twin: { type: 'infrastructure', labelField: 'assetType', stateFields: ['healthIndex', 'criticality'] },
    },
    events: [
      {
        type: 'infrastructure.asset-health.updated.v1',
        summary: 'Health index of an asset changed.',
        fields: {
          assetId: 'string',
          assetType: 'string',
          governorate: 'gov',
          healthIndex: 'unit',
          criticality: 'string',
          observedAt: 'date',
        },
      },
      {
        type: 'infrastructure.failure.predicted.v1',
        summary: 'An asset is predicted to fail within a horizon.',
        fields: {
          predictionId: 'string',
          assetId: 'string',
          assetType: 'string',
          governorate: 'gov',
          horizonDays: 'int',
          probability: 'unit',
          consequence: 'text',
          predictedAt: 'date',
        },
      },
      {
        type: 'infrastructure.maintenance.scheduled.v1',
        summary: 'A work order was scheduled.',
        fields: {
          orderId: 'string',
          assetId: 'string',
          governorate: 'gov',
          scheduledFor: 'date',
          estimatedCostTnd: 'number',
          priority: 'enum:low|standard|high|emergency',
        },
      },
    ],
    apis: [
      { archetype: 'health' },
      { archetype: 'list', module: 'national-infrastructure-digital-twin' },
      { archetype: 'get', module: 'national-infrastructure-digital-twin' },
      { archetype: 'create', module: 'national-infrastructure-digital-twin' },
      {
        archetype: 'ai',
        method: 'POST',
        path: '/maintenance/predict',
        module: 'predictive-infrastructure-maintenance',
        summary: 'Predict failure for an asset and warn everyone downstream of it.',
        input: { assetId: 'string', horizonDays: 'int?' },
        output: {
          predictionId: 'string',
          assetId: 'string',
          assetType: 'string',
          governorate: 'gov',
          horizonDays: 'int',
          probability: 'unit',
          consequence: 'text',
          predictedAt: 'date',
        },
        publishes: 'infrastructure.failure.predicted.v1',
      },
      {
        archetype: 'analytics',
        method: 'GET',
        path: '/assets/health',
        module: 'national-infrastructure-digital-twin',
        summary: 'Asset health by governorate.',
        groupBy: 'governorate',
        publishes: 'infrastructure.asset-health.updated.v1',
      },
      { archetype: 'signals' },
      { archetype: 'twins' },
    ],
    ai: ['failure prediction', 'maintenance prioritisation', 'strain anomaly detection'],
    iot: ['vibration', 'structural strain', 'water level', 'energy load', 'temperature'],
    twin: ['asset twin', 'network twin'],
  },

  // 20 -----------------------------------------------------------------
  {
    id: 'land',
    name: 'National Land Intelligence System',
    ministry: 'State Property & Land Affairs',
    summary: 'Parcels, zoning and whether a site is actually a good idea.',
    mission:
      'Answer "can this be built here, and should it" with evidence from every other ministry rather than with a map alone.',
    modules: [
      {
        id: 'tunisia-land-digital-twin',
        name: 'Tunisia Land Digital Twin',
        purpose: 'Parcels, zoning and current use.',
      },
      { id: 'ai-site-planner', name: 'AI Site Planner', purpose: 'Multi-criteria site suitability scoring.' },
      {
        id: 'public-asset-intelligence',
        name: 'Public Asset Intelligence',
        purpose: 'What the State owns and whether it is used.',
      },
    ],
    owns: ['LandParcelRef', 'PublicAssetRef', 'ZoningRuleRef'],
    entity: {
      collection: 'parcels',
      label: 'Land parcel',
      fields: {
        zoning: 'enum:agricultural|residential|industrial|protected|touristic|public|unzoned',
        governorate: 'gov',
        location: 'geo',
        areaHectares: 'number',
        ownership: 'enum:public|private|collective|unknown',
        currentUse: 'string',
        suitabilityScore: 'unit',
        floodRisk: 'unit',
      },
      seed: 50,
      twin: { type: 'asset', labelField: 'zoning', stateFields: ['suitabilityScore', 'floodRisk'] },
    },
    events: [
      {
        type: 'land.parcel.updated.v1',
        summary: 'A parcel record changed.',
        fields: {
          parcelId: 'string',
          governorate: 'gov',
          zoning: 'string',
          areaHectares: 'number',
          ownership: 'string',
          updatedAt: 'date',
        },
      },
      {
        type: 'land.zoning.changed.v1',
        summary: 'Zoning changed — several ministries must re-plan.',
        fields: {
          parcelId: 'string',
          governorate: 'gov',
          previousZoning: 'string',
          newZoning: 'string',
          reason: 'text',
          changedAt: 'date',
        },
      },
      {
        type: 'land.site-suitability.scored.v1',
        summary: 'A site was scored for a proposed use.',
        fields: {
          evaluationId: 'string',
          parcelId: 'string',
          proposedUse: 'string',
          governorate: 'gov',
          score: 'unit',
          constraints: 'string[]',
          scoredAt: 'date',
        },
      },
    ],
    apis: [
      { archetype: 'health' },
      { archetype: 'list', module: 'tunisia-land-digital-twin' },
      { archetype: 'get', module: 'tunisia-land-digital-twin' },
      { archetype: 'create', module: 'tunisia-land-digital-twin', publishes: 'land.parcel.updated.v1' },
      {
        archetype: 'ai',
        method: 'POST',
        path: '/siting/evaluate',
        module: 'ai-site-planner',
        summary:
          'Score a parcel for a proposed use against water, risk, mobility and environment constraints.',
        input: { parcelId: 'string', proposedUse: 'string' },
        output: {
          evaluationId: 'string',
          parcelId: 'string',
          proposedUse: 'string',
          governorate: 'gov',
          score: 'unit',
          constraints: 'string[]',
          scoredAt: 'date',
        },
        publishes: 'land.site-suitability.scored.v1',
      },
      {
        archetype: 'analytics',
        method: 'GET',
        path: '/parcels/pressure',
        module: 'public-asset-intelligence',
        summary: 'Land pressure by governorate.',
        groupBy: 'governorate',
      },
      { archetype: 'signals' },
      { archetype: 'twins' },
    ],
    ai: ['multi-criteria siting', 'zoning conflict detection', 'unused asset detection'],
    iot: ['soil moisture', 'water level', 'structural strain'],
    twin: ['parcel twin', 'public asset twin'],
  },

  // 21 -----------------------------------------------------------------
  {
    id: 'environment',
    name: 'Environmental Nervous System',
    ministry: 'Environment',
    summary: 'The country senses itself: air, water, climate and the circular use of what is thrown away.',
    mission:
      'Publish environmental truth continuously and early enough that other ministries can act on it rather than report it.',
    modules: [
      {
        id: 'national-environmental-sensor-network',
        name: 'National Environmental Sensor Network',
        purpose: 'Air, water and noise observations everywhere.',
      },
      {
        id: 'climate-digital-twin',
        name: 'Climate Digital Twin',
        purpose: 'Projections and climate risk per zone.',
      },
      {
        id: 'circular-resource-ai',
        name: 'Circular Resource AI',
        purpose: 'Waste streams and their possible reuse.',
      },
    ],
    owns: ['EnvironmentalObservation', 'ClimateProjectionRef', 'WasteStreamRef'],
    entity: {
      collection: 'stations',
      label: 'Environmental station',
      fields: {
        governorate: 'gov',
        location: 'geo',
        pm25: 'number',
        no2: 'number',
        waterTurbidity: 'number',
        noiseDb: 'number',
        temperature: 'number',
        climateRisk: 'unit',
        droughtIndex: 'unit',
      },
      seed: 40,
      twin: {
        type: 'environment-system',
        labelField: 'governorate',
        stateFields: ['pm25', 'climateRisk', 'droughtIndex'],
      },
    },
    events: [
      {
        type: 'environment.air-quality.updated.v1',
        summary: 'Air quality at a station. Health, Education, Mobility and Tourism all react to it.',
        fields: {
          stationId: 'string',
          governorate: 'gov',
          location: 'geo',
          pm25: 'number',
          no2: 'number',
          airQualityIndex: 'number',
          observedAt: 'date',
        },
      },
      {
        type: 'environment.water-quality.updated.v1',
        summary: 'Water quality at a station.',
        fields: {
          stationId: 'string',
          governorate: 'gov',
          turbidityNtu: 'number',
          salinityGl: 'number',
          potable: 'bool',
          observedAt: 'date',
        },
      },
      {
        type: 'environment.climate-risk.updated.v1',
        summary: 'Climate risk for a zone: drought, heat, flood.',
        fields: {
          governorate: 'gov',
          droughtIndex: 'unit',
          heatRisk: 'unit',
          floodRisk: 'unit',
          horizonMonths: 'int',
          updatedAt: 'date',
        },
      },
      {
        type: 'environment.waste-stream.updated.v1',
        summary: 'A waste stream volume or composition changed.',
        fields: {
          streamId: 'string',
          governorate: 'gov',
          material: 'string',
          tonnesPerYear: 'number',
          recoverable: 'unit',
          updatedAt: 'date',
        },
      },
    ],
    apis: [
      { archetype: 'health' },
      { archetype: 'list', module: 'national-environmental-sensor-network' },
      { archetype: 'get', module: 'national-environmental-sensor-network' },
      { archetype: 'create', module: 'national-environmental-sensor-network' },
      {
        archetype: 'analytics',
        method: 'GET',
        path: '/air-quality',
        module: 'national-environmental-sensor-network',
        summary: 'Air quality by governorate.',
        groupBy: 'governorate',
        publishes: 'environment.air-quality.updated.v1',
      },
      {
        archetype: 'ai',
        method: 'POST',
        path: '/climate/projection',
        module: 'climate-digital-twin',
        summary: 'Project climate risk for a governorate and warn the ministries it constrains.',
        input: { governorate: 'gov', horizonMonths: 'int?' },
        output: {
          governorate: 'gov',
          droughtIndex: 'unit',
          heatRisk: 'unit',
          floodRisk: 'unit',
          horizonMonths: 'int',
          updatedAt: 'date',
        },
        publishes: 'environment.climate-risk.updated.v1',
      },
      { archetype: 'signals' },
      { archetype: 'twins' },
    ],
    ai: ['pollution source attribution', 'climate projection', 'waste reuse matching'],
    iot: ['air quality', 'water quality', 'noise', 'temperature', 'humidity', 'rainfall', 'wind speed'],
    twin: ['station twin', 'climate zone twin'],
  },

  // 22 -----------------------------------------------------------------
  {
    id: 'tourism',
    name: 'Tunisia Immersive Tourism OS',
    ministry: 'Tourism',
    summary: 'Visitor flows, site pressure and experiences that exist before the visitor arrives.',
    mission:
      'Spread visitors instead of concentrating them, using signals the country already produces — and protect the sites that make the visit worth it.',
    modules: [
      {
        id: 'tourism-digital-twin',
        name: 'Tourism Digital Twin',
        purpose: 'Site capacity, pressure and seasonality.',
      },
      { id: 'ar-tunisia', name: 'AR Tunisia', purpose: 'Anchored augmented-reality scenes at real sites.' },
      {
        id: 'ai-tourism-flow-engine',
        name: 'AI Tourism Flow Engine',
        purpose: 'Itineraries that redistribute pressure.',
      },
    ],
    owns: ['TourismAssetRef', 'VisitorFlowRef', 'ARSceneRef'],
    entity: {
      collection: 'sites',
      label: 'Tourism site',
      fields: {
        assetType: 'enum:hotel|beach|medina|archaeological|oasis|trail|festival|museum',
        governorate: 'gov',
        location: 'geo',
        capacity: 'int',
        visitorsWeek: 'int',
        pressureIndex: 'unit',
        seasonality: 'enum:year-round|summer|winter|event',
        arScenes: 'int',
      },
      seed: 36,
      twin: { type: 'facility', labelField: 'assetType', stateFields: ['pressureIndex', 'visitorsWeek'] },
    },
    events: [
      {
        type: 'tourism.visitor-flow.updated.v1',
        summary: 'Visitor volume at a site or zone.',
        fields: {
          siteId: 'string',
          governorate: 'gov',
          visitorsWeek: 'int',
          originMix: 'string[]',
          observedAt: 'date',
        },
      },
      {
        type: 'tourism.site-pressure.detected.v1',
        summary: 'A site is over its sustainable capacity.',
        fields: {
          siteId: 'string',
          governorate: 'gov',
          pressureIndex: 'unit',
          capacity: 'int',
          visitorsWeek: 'int',
          detectedAt: 'date',
        },
      },
      {
        type: 'tourism.experience.published.v1',
        summary: 'A new itinerary or AR experience is available.',
        fields: {
          experienceId: 'string',
          title: 'string',
          governorate: 'gov',
          sites: 'string[]',
          durationHours: 'int',
          publishedAt: 'date',
        },
      },
    ],
    apis: [
      { archetype: 'health' },
      { archetype: 'list', module: 'tourism-digital-twin' },
      { archetype: 'get', module: 'tourism-digital-twin' },
      { archetype: 'create', module: 'tourism-digital-twin' },
      {
        archetype: 'ai',
        method: 'POST',
        path: '/itinerary',
        module: 'ai-tourism-flow-engine',
        summary: 'Build an itinerary that avoids saturated sites and bad air days.',
        input: { interests: 'string[]', governorate: 'gov?', days: 'int?' },
        output: {
          experienceId: 'string',
          title: 'string',
          governorate: 'gov',
          sites: 'string[]',
          durationHours: 'int',
          publishedAt: 'date',
        },
        publishes: 'tourism.experience.published.v1',
      },
      {
        archetype: 'analytics',
        method: 'GET',
        path: '/flows',
        module: 'tourism-digital-twin',
        summary: 'Visitor pressure by governorate.',
        groupBy: 'governorate',
        publishes: 'tourism.visitor-flow.updated.v1',
      },
      { archetype: 'signals' },
      { archetype: 'twins' },
    ],
    ai: ['itinerary generation', 'pressure forecasting', 'multilingual site narration'],
    iot: ['occupancy', 'air quality', 'noise', 'temperature'],
    twin: ['site twin', 'visitor flow twin'],
  },

  // 23 -----------------------------------------------------------------
  {
    id: 'life-care',
    name: 'Life & Care Intelligence OS',
    ministry: 'Family, Women, Childhood & Seniors',
    summary: 'Life events, care capacity and the path to economic independence.',
    mission:
      'Follow a life journey across the ministries that touch it, so that support arrives at the transition instead of after it.',
    modules: [
      {
        id: 'life-journey-ai',
        name: 'Life Journey AI',
        purpose: 'Life events and the support each one should trigger.',
      },
      {
        id: 'smart-care-network',
        name: 'Smart Care Network',
        purpose: 'Care facilities, capacity and coverage.',
      },
      {
        id: 'economic-independence-engine',
        name: 'Economic Independence Engine',
        purpose: 'The concrete path from support to autonomy.',
      },
    ],
    owns: ['CareCohortRef', 'CareFacilityRef', 'LifeEventRef'],
    entity: {
      collection: 'facilities',
      label: 'Care facility',
      fields: {
        facilityType: 'enum:nursery|childrens-centre|womens-centre|elder-home|day-care|shelter',
        governorate: 'gov',
        location: 'geo',
        capacity: 'int',
        occupied: 'int',
        waitingList: 'int',
        independenceScore: 'unit',
        services: 'string[]',
      },
      seed: 32,
      twin: { type: 'facility', labelField: 'facilityType', stateFields: ['occupied', 'waitingList'] },
    },
    events: [
      {
        type: 'care.life-event.recorded.v1',
        summary: 'A life transition was recorded for a cohort.',
        fields: {
          eventId: 'string',
          cohortId: 'string',
          eventType: 'enum:birth|schooling|graduation|employment|illness|retirement|bereavement|relocation',
          governorate: 'gov',
          people: 'int',
          recordedAt: 'date',
        },
      },
      {
        type: 'care.support-need.detected.v1',
        summary: 'A support need was inferred from a life event and other ministry signals.',
        fields: {
          needId: 'string',
          cohortId: 'string',
          needType: 'string',
          governorate: 'gov',
          urgency: 'enum:normal|high|critical',
          detectedAt: 'date',
        },
      },
      {
        type: 'care.facility-capacity.updated.v1',
        summary: 'Care facility capacity changed.',
        fields: {
          facilityId: 'string',
          governorate: 'gov',
          capacity: 'int',
          occupied: 'int',
          waitingList: 'int',
          observedAt: 'date',
        },
      },
    ],
    apis: [
      { archetype: 'health' },
      { archetype: 'list', module: 'smart-care-network' },
      { archetype: 'get', module: 'smart-care-network' },
      { archetype: 'create', module: 'smart-care-network' },
      {
        archetype: 'ai',
        method: 'POST',
        path: '/life-event',
        module: 'life-journey-ai',
        summary: 'Record a life event and infer the support it should trigger.',
        input: { cohortId: 'string', eventType: 'string', governorate: 'gov' },
        output: {
          needId: 'string',
          cohortId: 'string',
          needType: 'string',
          governorate: 'gov',
          urgency: 'enum:normal|high|critical',
          detectedAt: 'date',
        },
        publishes: 'care.support-need.detected.v1',
      },
      {
        archetype: 'analytics',
        method: 'GET',
        path: '/coverage',
        module: 'economic-independence-engine',
        summary: 'Care coverage by governorate.',
        groupBy: 'governorate',
        publishes: 'care.facility-capacity.updated.v1',
      },
      { archetype: 'signals' },
      { archetype: 'twins' },
    ],
    ai: ['life-event to support inference', 'independence path planning', 'coverage gap detection'],
    iot: ['occupancy', 'temperature', 'wearable heart rate'],
    twin: ['care facility twin', 'life cohort twin'],
  },

  // 24 -----------------------------------------------------------------
  {
    id: 'culture',
    name: 'Tunisia Cultural Intelligence Network',
    ministry: 'Culture',
    summary: 'Cultural assets, immersive access and a creative economy that can be measured.',
    mission:
      'Make culture an infrastructure with a state — conserved, visited, funded — rather than a calendar of events.',
    modules: [
      {
        id: 'tunisia-cultural-digital-twin',
        name: 'Tunisia Cultural Digital Twin',
        purpose: 'Condition and use of every cultural asset.',
      },
      {
        id: 'immersive-tunisia',
        name: 'Immersive Tunisia',
        purpose: 'Digitised works and immersive access.',
      },
      {
        id: 'creative-economy-ai-network',
        name: 'Creative Economy AI Network',
        purpose: 'Creative activity, audience and revenue.',
      },
    ],
    owns: ['CulturalAssetRef', 'CreativeWorkRef', 'CulturalEventRef'],
    entity: {
      collection: 'assets',
      label: 'Cultural asset',
      fields: {
        assetType: 'enum:monument|museum|manuscript|craft|performance|site|archive',
        governorate: 'gov',
        location: 'geo',
        period: 'string',
        conditionIndex: 'unit',
        visitorsMonth: 'int',
        digitised: 'bool',
        protectionStatus: 'enum:none|national|unesco|at-risk',
      },
      seed: 38,
      twin: {
        type: 'heritage-site',
        labelField: 'assetType',
        stateFields: ['conditionIndex', 'visitorsMonth'],
      },
    },
    events: [
      {
        type: 'culture.asset-condition.updated.v1',
        summary: 'Condition of a cultural asset changed.',
        fields: {
          assetId: 'string',
          governorate: 'gov',
          conditionIndex: 'unit',
          protectionStatus: 'string',
          observedAt: 'date',
        },
      },
      {
        type: 'culture.event.scheduled.v1',
        summary: 'A cultural event was scheduled — mobility, safety and tourism plan against it.',
        fields: {
          eventId: 'string',
          title: 'string',
          governorate: 'gov',
          location: 'geo',
          expectedAttendance: 'int',
          startsAt: 'date',
        },
      },
      {
        type: 'culture.creative-economy.updated.v1',
        summary: 'Creative activity and revenue for a governorate.',
        fields: {
          governorate: 'gov',
          activeCreators: 'int',
          revenueTnd: 'number',
          dominantDiscipline: 'string',
          updatedAt: 'date',
        },
      },
    ],
    apis: [
      { archetype: 'health' },
      { archetype: 'list', module: 'tunisia-cultural-digital-twin' },
      { archetype: 'get', module: 'tunisia-cultural-digital-twin' },
      { archetype: 'create', module: 'tunisia-cultural-digital-twin' },
      {
        archetype: 'ai',
        method: 'POST',
        path: '/events/plan',
        module: 'creative-economy-ai-network',
        summary: 'Plan a cultural event and warn the ministries whose load it will change.',
        input: { title: 'text', governorate: 'gov', expectedAttendance: 'int?' },
        output: {
          eventId: 'string',
          title: 'string',
          governorate: 'gov',
          location: 'geo',
          expectedAttendance: 'int',
          startsAt: 'date',
        },
        publishes: 'culture.event.scheduled.v1',
      },
      {
        archetype: 'analytics',
        method: 'GET',
        path: '/assets/condition',
        module: 'tunisia-cultural-digital-twin',
        summary: 'Cultural asset condition by governorate.',
        groupBy: 'governorate',
        publishes: 'culture.asset-condition.updated.v1',
      },
      { archetype: 'signals' },
      { archetype: 'twins' },
    ],
    ai: ['condition forecasting', 'audience recommendation', 'archive summarisation'],
    iot: ['humidity', 'temperature', 'occupancy', 'vibration'],
    twin: ['cultural asset twin', 'creative economy twin'],
  },
];
