/**
 * ARCHITECTURE SOURCE OF TRUTH — services 1 to 12.
 *
 * Everything generated (service code, manifests, contracts, OpenAPI, AsyncAPI,
 * RELATIONS.md, the portal graph, the validator's expectations) is derived from
 * this file and its sibling. Edit here, run `pnpm generate`, and the whole
 * platform follows. Editing a generated file by hand is how architectures rot.
 *
 * FIELD DSL (used for entities, event payloads and AI outputs)
 *   'id' 'string' 'text' 'number' 'int' 'unit'(0..1) 'bool' 'date'
 *   'geo'  -> shared GeoLocation      'gov' -> governorate code
 *   'enum:a|b|c'                      'string[]' 'number[]'
 *   suffix '?' anywhere -> optional   e.g. 'number?'
 */

export const SERVICES_PART_1 = [
  // 1 ------------------------------------------------------------------
  {
    id: 'justice',
    name: 'Justice Intelligence OS',
    ministry: 'Justice',
    summary: 'Case flow, legal knowledge and court capacity as one observable system.',
    mission:
      'Make the journey of a case legible end to end: where it is, what it is waiting on, and which court is saturated — so delay becomes a measurable, addressable quantity rather than an anecdote.',
    modules: [
      {
        id: 'justice-digital-twin',
        name: 'Justice Digital Twin',
        purpose: 'A live twin per court: pending load, average delay, saturation.',
      },
      {
        id: 'ai-legal-navigator',
        name: 'AI Legal Navigator',
        purpose: 'RAG over published legal texts so a citizen question gets a sourced answer.',
      },
      {
        id: 'smart-justice-workflow',
        name: 'Smart Justice Workflow',
        purpose: 'Case stages, deadlines and the events other ministries need.',
      },
    ],
    owns: ['CaseRef', 'CourtRef', 'LegalTextRef'],
    entity: {
      collection: 'cases',
      label: 'Case',
      fields: {
        reference: 'string',
        matter: 'enum:civil|commercial|administrative|labour|family|penal',
        court: 'string',
        stage: 'enum:filed|instruction|hearing|deliberation|decided|appealed',
        openedAt: 'date',
        delayDays: 'int',
        complexity: 'unit',
        governorate: 'gov',
      },
      seed: 40,
      twin: { type: 'process', labelField: 'reference', stateFields: ['stage', 'delayDays'] },
    },
    events: [
      {
        type: 'justice.case.filed.v1',
        summary: 'A new case entered the system.',
        fields: { caseId: 'string', matter: 'string', court: 'string', governorate: 'gov', filedAt: 'date' },
      },
      {
        type: 'justice.case.decided.v1',
        summary: 'A case reached a decision.',
        fields: {
          caseId: 'string',
          matter: 'string',
          durationDays: 'int',
          governorate: 'gov',
          decidedAt: 'date',
        },
      },
      {
        type: 'justice.court-load.updated.v1',
        summary: 'Pending load and saturation for a court.',
        fields: {
          court: 'string',
          governorate: 'gov',
          pendingCases: 'int',
          saturation: 'unit',
          averageDelayDays: 'int',
          observedAt: 'date',
        },
      },
      {
        type: 'justice.legal-text.published.v1',
        summary: 'A legal text became applicable — other ministries may need to adapt.',
        fields: {
          textId: 'string',
          title: 'string',
          domain: 'string',
          effectiveFrom: 'date',
          summary: 'text',
        },
      },
    ],
    apis: [
      { archetype: 'health' },
      { archetype: 'list', module: 'smart-justice-workflow' },
      { archetype: 'get', module: 'smart-justice-workflow' },
      { archetype: 'create', module: 'smart-justice-workflow', publishes: 'justice.case.filed.v1' },
      {
        archetype: 'ai',
        method: 'POST',
        path: '/navigator/ask',
        module: 'ai-legal-navigator',
        summary: 'Ask a legal question; answered only from the published texts held by this service.',
        input: { question: 'text', domain: 'string?' },
        output: { answer: 'text', citedTexts: 'string[]', confidence: 'unit', caution: 'text' },
      },
      {
        archetype: 'analytics',
        method: 'GET',
        path: '/courts/load',
        module: 'justice-digital-twin',
        summary: 'Pending load and saturation per court.',
        groupBy: 'court',
        publishes: 'justice.court-load.updated.v1',
      },
      { archetype: 'signals' },
      { archetype: 'twins' },
    ],
    ai: ['RAG over legal texts', 'case-duration forecasting', 'matter classification'],
    iot: ['courthouse occupancy sensors', 'hearing-room environment'],
    twin: ['court twin (load, delay, saturation)', 'case-flow process twin'],
  },

  // 2 ------------------------------------------------------------------
  {
    id: 'resilience',
    name: 'National Resilience Command System',
    ministry: 'Interior / Civil Protection',
    summary: 'Crisis declaration, relief logistics and a mesh that survives the network going down.',
    mission:
      'Hold one shared picture of a crisis across every ministry, and turn it into a relief plan with named resources — because in a crisis the failure is almost never lack of resources, it is lack of a shared picture.',
    modules: [
      {
        id: 'national-resilience-digital-twin',
        name: 'National Resilience Digital Twin',
        purpose: 'Live state of every declared crisis and the zones it covers.',
      },
      {
        id: 'autonomous-crisis-logistics',
        name: 'Autonomous Crisis Logistics',
        purpose: 'Turns needs into a resourced, sequenced relief plan.',
      },
      {
        id: 'emergency-mesh-network',
        name: 'Emergency Mesh Network',
        purpose: 'Store-and-forward node health when normal connectivity is gone.',
      },
    ],
    owns: ['CrisisRef', 'ReliefPlanRef', 'MeshNodeRef'],
    entity: {
      collection: 'crises',
      label: 'Crisis',
      fields: {
        kind: 'enum:flood|drought|earthquake|fire|epidemic|industrial|storm|power-failure',
        severity: 'enum:watch|alert|major|catastrophic',
        status: 'enum:declared|responding|stabilised|closed',
        governorate: 'gov',
        location: 'geo',
        declaredAt: 'date',
        affectedPeople: 'int',
        peopleAtRisk: 'int',
      },
      seed: 8,
      twin: { type: 'region', labelField: 'kind', stateFields: ['status', 'severity', 'affectedPeople'] },
    },
    events: [
      {
        type: 'resilience.crisis.declared.v1',
        summary: 'A crisis is declared — the single signal that reconfigures the whole platform.',
        fields: {
          crisisId: 'string',
          kind: 'string',
          severity: 'string',
          governorate: 'gov',
          location: 'geo',
          affectedPeople: 'int',
          declaredAt: 'date',
        },
      },
      {
        type: 'resilience.relief-plan.updated.v1',
        summary: 'The resourced relief plan for a crisis changed.',
        fields: {
          crisisId: 'string',
          governorate: 'gov',
          requiredResources: 'string[]',
          coveragePct: 'unit',
          updatedAt: 'date',
        },
      },
      {
        type: 'resilience.resource-request.created.v1',
        summary: 'Resilience needs a resource another ministry controls.',
        fields: {
          requestId: 'string',
          crisisId: 'string',
          resourceType: 'string',
          quantity: 'int',
          governorate: 'gov',
          urgency: 'enum:normal|high|critical',
        },
      },
      {
        type: 'resilience.mesh-node.status.v1',
        summary: 'Emergency mesh node reachability.',
        fields: {
          nodeId: 'string',
          governorate: 'gov',
          reachable: 'bool',
          batteryPct: 'unit',
          neighbours: 'int',
          observedAt: 'date',
        },
      },
    ],
    apis: [
      { archetype: 'health' },
      { archetype: 'list', module: 'national-resilience-digital-twin' },
      { archetype: 'get', module: 'national-resilience-digital-twin' },
      {
        archetype: 'create',
        module: 'national-resilience-digital-twin',
        publishes: 'resilience.crisis.declared.v1',
      },
      {
        archetype: 'ai',
        method: 'POST',
        path: '/logistics/plan',
        module: 'autonomous-crisis-logistics',
        summary: 'Produce a relief plan for a crisis and broadcast it.',
        input: { crisisId: 'string', horizonHours: 'int?' },
        output: {
          crisisId: 'string',
          governorate: 'gov',
          requiredResources: 'string[]',
          coveragePct: 'unit',
          updatedAt: 'date',
        },
        publishes: 'resilience.relief-plan.updated.v1',
      },
      {
        archetype: 'analytics',
        method: 'GET',
        path: '/mesh/nodes',
        module: 'emergency-mesh-network',
        summary: 'Mesh node reachability by governorate.',
        groupBy: 'governorate',
      },
      { archetype: 'signals' },
      { archetype: 'twins' },
    ],
    ai: ['relief planning under constraint', 'crisis severity classification', 'multi-hazard scenario agent'],
    iot: ['mesh node telemetry', 'water level', 'rainfall', 'wind speed'],
    twin: ['crisis twin per event', 'governorate resilience twin'],
  },

  // 3 ------------------------------------------------------------------
  {
    id: 'safety-emergency',
    name: 'National Safety & Emergency Grid',
    ministry: 'Interior',
    summary: 'Incidents, dispatch and road risk — the fastest loop on the platform.',
    mission:
      'Receive an incident from anywhere, understand it in seconds, and pull the nearest capable resource from whichever ministry owns it.',
    modules: [
      {
        id: 'national-emergency-brain',
        name: 'National Emergency Brain',
        purpose: 'Triage, severity and the dispatch decision.',
      },
      {
        id: 'ai-road-safety-grid',
        name: 'AI Road Safety Grid',
        purpose: 'Continuous risk scoring of road segments.',
      },
      {
        id: 'smart-civil-services',
        name: 'Smart Civil Services',
        purpose: 'Civil requests that do not need an emergency response.',
      },
    ],
    owns: ['IncidentRef', 'PatrolUnitRef'],
    entity: {
      collection: 'incidents',
      label: 'Incident',
      fields: {
        incidentType:
          'enum:road-accident|fire|flood|medical|industrial|power-outage|water-outage|security|environmental',
        severity: 'enum:minor|moderate|major|critical',
        status: 'enum:open|dispatched|contained|resolved',
        location: 'geo',
        governorate: 'gov',
        declaredAt: 'date',
        casualties: 'int',
      },
      seed: 30,
      twin: { type: 'process', labelField: 'incidentType', stateFields: ['status', 'severity'] },
    },
    events: [
      {
        type: 'emergency.incident.created.v1',
        summary: 'An incident was reported. The most widely consumed event on the platform.',
        fields: {
          incidentId: 'string',
          incidentType: 'string',
          severity: 'string',
          location: 'geo',
          governorate: 'gov',
          casualties: 'int',
          declaredAt: 'date',
        },
      },
      {
        type: 'emergency.incident.resolved.v1',
        summary: 'An incident is closed, with how long it took.',
        fields: {
          incidentId: 'string',
          incidentType: 'string',
          governorate: 'gov',
          durationMinutes: 'int',
          resolvedAt: 'date',
        },
      },
      {
        type: 'emergency.resource.requested.v1',
        summary: 'Emergency asks another ministry for a specific resource.',
        fields: {
          requestId: 'string',
          incidentId: 'string',
          resourceType: 'string',
          location: 'geo',
          urgency: 'enum:normal|high|critical',
          requestedAt: 'date',
        },
      },
      {
        type: 'emergency.road-risk.updated.v1',
        summary: 'Risk score for a road segment changed.',
        fields: {
          segmentId: 'string',
          governorate: 'gov',
          riskScore: 'unit',
          drivers: 'string[]',
          observedAt: 'date',
        },
      },
    ],
    apis: [
      { archetype: 'health' },
      { archetype: 'list', module: 'national-emergency-brain' },
      { archetype: 'get', module: 'national-emergency-brain' },
      { archetype: 'create', module: 'national-emergency-brain', publishes: 'emergency.incident.created.v1' },
      {
        archetype: 'ai',
        method: 'POST',
        path: '/triage',
        module: 'national-emergency-brain',
        summary: 'Classify an incoming report and say what to dispatch.',
        input: { report: 'text', governorate: 'gov?' },
        output: {
          severity: 'enum:minor|moderate|major|critical',
          incidentType: 'string',
          recommendedResources: 'string[]',
          reasoning: 'text',
          confidence: 'unit',
        },
      },
      {
        archetype: 'analytics',
        method: 'GET',
        path: '/road-risk',
        module: 'ai-road-safety-grid',
        summary: 'Road risk by governorate, blending incidents with weather and traffic signals.',
        groupBy: 'governorate',
        publishes: 'emergency.road-risk.updated.v1',
      },
      { archetype: 'signals' },
      { archetype: 'twins' },
    ],
    ai: ['incident triage', 'road risk scoring', 'dispatch recommendation agent'],
    iot: ['traffic flow', 'air quality', 'rainfall', 'vibration'],
    twin: ['incident twin', 'road segment twin'],
  },

  // 4 ------------------------------------------------------------------
  {
    id: 'global-tunisia',
    name: 'Global Tunisia Network',
    ministry: 'Foreign Affairs',
    summary: 'The diaspora as a live network: consular load, skills abroad, opportunities home.',
    mission:
      'Treat Tunisians abroad as a connected part of the national system — a source of skills, investment and demand, not a mailing list.',
    modules: [
      {
        id: 'diaspora-intelligence-graph',
        name: 'Diaspora Intelligence Graph',
        purpose: 'Aggregate, privacy-safe picture of skills and presence abroad.',
      },
      {
        id: 'ai-consular-twin',
        name: 'AI Consular Twin',
        purpose: 'Consular demand and processing time per post.',
      },
      {
        id: 'global-opportunity-engine',
        name: 'Global Opportunity Engine',
        purpose: 'Matches opportunities at home to capabilities abroad.',
      },
    ],
    owns: ['DiasporaCohortRef', 'ConsulateRef', 'GlobalOpportunityRef'],
    entity: {
      collection: 'consulates',
      label: 'Consular post',
      fields: {
        country: 'string',
        city: 'string',
        cohortSize: 'int',
        pendingRequests: 'int',
        averageProcessingDays: 'int',
        topSkills: 'string[]',
        load: 'unit',
      },
      seed: 16,
      twin: { type: 'facility', labelField: 'city', stateFields: ['load', 'pendingRequests'] },
    },
    events: [
      {
        type: 'global.consular-request.created.v1',
        summary: 'A consular request was filed abroad.',
        fields: {
          requestId: 'string',
          post: 'string',
          country: 'string',
          requestType: 'enum:passport|civil-status|visa|assistance|investment',
          filedAt: 'date',
        },
      },
      {
        type: 'global.opportunity.published.v1',
        summary: 'An opportunity at home is opened to the diaspora.',
        fields: {
          opportunityId: 'string',
          title: 'string',
          sector: 'string',
          governorate: 'gov',
          requiredSkills: 'string[]',
          publishedAt: 'date',
        },
      },
      {
        type: 'global.diaspora-signal.updated.v1',
        summary: 'Aggregate diaspora signal: skills concentration and investment appetite per country.',
        fields: {
          country: 'string',
          cohortSize: 'int',
          topSkills: 'string[]',
          investmentAppetite: 'unit',
          observedAt: 'date',
        },
      },
    ],
    apis: [
      { archetype: 'health' },
      { archetype: 'list', module: 'ai-consular-twin' },
      { archetype: 'get', module: 'ai-consular-twin' },
      { archetype: 'create', module: 'ai-consular-twin' },
      {
        archetype: 'ai',
        method: 'POST',
        path: '/opportunities/match',
        module: 'global-opportunity-engine',
        summary: 'Match a national need to diaspora capability.',
        input: { need: 'text', sector: 'string?', governorate: 'gov?' },
        output: {
          opportunityId: 'string',
          title: 'string',
          sector: 'string',
          governorate: 'gov',
          requiredSkills: 'string[]',
          publishedAt: 'date',
        },
        publishes: 'global.opportunity.published.v1',
      },
      {
        archetype: 'analytics',
        method: 'GET',
        path: '/diaspora/stats',
        module: 'diaspora-intelligence-graph',
        summary: 'Cohorts and skills by country.',
        groupBy: 'country',
      },
      { archetype: 'signals' },
      { archetype: 'twins' },
    ],
    ai: [
      'skill-to-opportunity matching',
      'consular demand forecasting',
      'multilingual request summarisation',
    ],
    iot: ['consular queue occupancy'],
    twin: ['consular post twin', 'country cohort twin'],
  },

  // 5 ------------------------------------------------------------------
  {
    id: 'treasury',
    name: 'Intelligent Treasury OS',
    ministry: 'Finance',
    summary: 'Where public money is, where it is committed, and what it is buying.',
    mission:
      'Make the budget a live object other ministries can query and react to — so a drought, an outage or an epidemic has a visible fiscal consequence the same day, not the following year.',
    modules: [
      {
        id: 'real-time-treasury-twin',
        name: 'Real-Time Treasury Twin',
        purpose: 'Live position of every budget line.',
      },
      {
        id: 'ai-public-budget-optimizer',
        name: 'AI Public Budget Optimizer',
        purpose: 'Reallocation proposals under an explicit constraint.',
      },
      { id: 'smart-aid-wallet', name: 'Smart Aid Wallet', purpose: 'Targeted, traceable aid disbursement.' },
    ],
    owns: ['FinancialProgramRef', 'BudgetLineRef', 'AidWalletRef'],
    entity: {
      collection: 'budgetLines',
      label: 'Budget line',
      fields: {
        programme: 'string',
        ministry: 'string',
        fiscalYear: 'int',
        allocatedTnd: 'number',
        committedTnd: 'number',
        governorate: 'gov',
        instrument: 'enum:budget-line|grant|subsidy|loan|guarantee|aid-wallet',
        priority: 'enum:low|standard|high|emergency',
      },
      seed: 48,
      twin: { type: 'process', labelField: 'programme', stateFields: ['committedTnd', 'priority'] },
    },
    events: [
      {
        type: 'treasury.budget-line.updated.v1',
        summary: 'A budget line moved.',
        fields: {
          lineId: 'string',
          programme: 'string',
          ministry: 'string',
          allocatedTnd: 'number',
          committedTnd: 'number',
          governorate: 'gov',
          updatedAt: 'date',
        },
      },
      {
        type: 'treasury.funding.approved.v1',
        summary: 'Funding was approved for another ministry request.',
        fields: {
          approvalId: 'string',
          requestedBy: 'string',
          amountTnd: 'number',
          purpose: 'text',
          governorate: 'gov',
          approvedAt: 'date',
        },
      },
      {
        type: 'treasury.aid.disbursed.v1',
        summary: 'Targeted aid reached a beneficiary cohort.',
        fields: {
          disbursementId: 'string',
          cohortId: 'string',
          amountTnd: 'number',
          governorate: 'gov',
          beneficiaries: 'int',
          disbursedAt: 'date',
        },
      },
      {
        type: 'treasury.fiscal-risk.flagged.v1',
        summary: 'A fiscal risk was detected — over-commitment, shock exposure, revenue gap.',
        fields: {
          riskId: 'string',
          driver: 'string',
          exposureTnd: 'number',
          governorate: 'gov',
          severity: 'enum:low|medium|high',
          flaggedAt: 'date',
        },
      },
    ],
    apis: [
      { archetype: 'health' },
      { archetype: 'list', module: 'real-time-treasury-twin' },
      { archetype: 'get', module: 'real-time-treasury-twin' },
      {
        archetype: 'create',
        module: 'real-time-treasury-twin',
        publishes: 'treasury.budget-line.updated.v1',
      },
      {
        archetype: 'ai',
        method: 'POST',
        path: '/budget/optimise',
        module: 'ai-public-budget-optimizer',
        summary: 'Propose a reallocation under a stated constraint, with its rationale.',
        input: { objective: 'text', governorate: 'gov?', maxShiftTnd: 'number?' },
        output: {
          riskId: 'string',
          driver: 'string',
          exposureTnd: 'number',
          governorate: 'gov',
          severity: 'enum:low|medium|high',
          flaggedAt: 'date',
        },
        publishes: 'treasury.fiscal-risk.flagged.v1',
      },
      {
        archetype: 'analytics',
        method: 'GET',
        path: '/position',
        module: 'real-time-treasury-twin',
        summary: 'Commitment rate by ministry.',
        groupBy: 'ministry',
      },
      { archetype: 'signals' },
      { archetype: 'twins' },
    ],
    ai: ['budget reallocation under constraint', 'fiscal anomaly detection', 'shock cost estimation'],
    iot: [],
    twin: ['budget line twin', 'programme twin'],
  },

  // 6 ------------------------------------------------------------------
  {
    id: 'national-digital-twin',
    name: 'Tunisia National Digital Twin',
    ministry: 'Planning / Prime Ministry',
    summary: 'The country as one queryable model, assembled from what the other 23 publish.',
    mission:
      'Hold the whole picture without owning anyone else data: aggregate references and signals, run scenarios across them, and hand every ministry back the context it cannot see alone.',
    modules: [
      {
        id: 'tunisia-digital-twin',
        name: 'Tunisia Digital Twin',
        purpose: 'Regional state assembled from every ministry signal.',
      },
      {
        id: 'national-scenario-engine',
        name: 'National Scenario Engine',
        purpose: 'What-if simulation across sectors.',
      },
      {
        id: 'regional-ai-planner',
        name: 'Regional AI Planner',
        purpose: 'Investment and priority proposals per governorate.',
      },
    ],
    owns: ['RegionStateRef', 'ScenarioRef'],
    entity: {
      collection: 'regionStates',
      label: 'Region state',
      fields: {
        governorate: 'gov',
        population: 'int',
        stressIndex: 'unit',
        waterStress: 'unit',
        airQualityIndex: 'number',
        healthLoad: 'unit',
        mobilityPressure: 'unit',
        economicActivity: 'unit',
        updatedAt: 'date',
      },
      seed: 24,
      twin: {
        type: 'region',
        labelField: 'governorate',
        stateFields: ['stressIndex', 'waterStress', 'healthLoad'],
      },
    },
    events: [
      {
        type: 'twin.state.updated.v1',
        summary: 'The national twin recomputed a region state.',
        fields: {
          governorate: 'gov',
          stressIndex: 'unit',
          drivers: 'string[]',
          contributingServices: 'string[]',
          updatedAt: 'date',
        },
      },
      {
        type: 'twin.scenario.completed.v1',
        summary: 'A cross-sector scenario finished running.',
        fields: {
          scenarioId: 'string',
          question: 'text',
          governorate: 'gov',
          outcome: 'text',
          impactedSectors: 'string[]',
          confidence: 'unit',
          completedAt: 'date',
        },
      },
      {
        type: 'twin.anomaly.detected.v1',
        summary: 'A region deviates from its own baseline across several sectors at once.',
        fields: {
          anomalyId: 'string',
          governorate: 'gov',
          metric: 'string',
          deviation: 'number',
          likelyCauses: 'string[]',
          detectedAt: 'date',
        },
      },
    ],
    apis: [
      { archetype: 'health' },
      { archetype: 'list', module: 'tunisia-digital-twin' },
      { archetype: 'get', module: 'tunisia-digital-twin' },
      {
        archetype: 'ai',
        method: 'POST',
        path: '/scenarios/run',
        module: 'national-scenario-engine',
        summary: 'Run a cross-sector what-if and broadcast the outcome.',
        input: { question: 'text', governorate: 'gov?', horizonMonths: 'int?' },
        output: {
          scenarioId: 'string',
          question: 'text',
          governorate: 'gov',
          outcome: 'text',
          impactedSectors: 'string[]',
          confidence: 'unit',
          completedAt: 'date',
        },
        publishes: 'twin.scenario.completed.v1',
      },
      {
        archetype: 'analytics',
        method: 'GET',
        path: '/regions/stress',
        module: 'regional-ai-planner',
        summary: 'Composite stress index per governorate, with the services that drove it.',
        groupBy: 'governorate',
        publishes: 'twin.state.updated.v1',
      },
      { archetype: 'signals' },
      { archetype: 'twins' },
    ],
    ai: ['cross-sector scenario simulation', 'multivariate anomaly detection', 'regional priority ranking'],
    iot: ['every sensor kind, as aggregate references'],
    twin: ['24 governorate twins', 'national composite twin'],
  },

  // 7 ------------------------------------------------------------------
  {
    id: 'social-mobility',
    name: 'Social Mobility OS',
    ministry: 'Social Affairs',
    summary: 'Household vulnerability and benefits that arrive without a form.',
    mission:
      'Detect need from signals other ministries already produce, instead of waiting for a household to prove it at a counter.',
    modules: [
      {
        id: 'social-digital-twin',
        name: 'Social Digital Twin',
        purpose: 'Vulnerability per household cohort, continuously updated.',
      },
      {
        id: 'zero-form-social-services',
        name: 'Zero-Form Social Services',
        purpose: 'Eligibility computed from existing signals.',
      },
      {
        id: 'social-mobility-ai',
        name: 'Social Mobility AI',
        purpose: 'What actually moves a cohort upward, by governorate.',
      },
    ],
    owns: ['HouseholdCohortRef', 'SocialBenefitRef'],
    entity: {
      collection: 'cohorts',
      label: 'Household cohort',
      fields: {
        governorate: 'gov',
        size: 'int',
        vulnerabilityIndex: 'unit',
        employmentRate: 'unit',
        schoolingRate: 'unit',
        healthAccess: 'unit',
        housingQuality: 'unit',
        benefitsActive: 'int',
      },
      seed: 36,
      twin: {
        type: 'citizen-cohort',
        labelField: 'governorate',
        stateFields: ['vulnerabilityIndex', 'benefitsActive'],
      },
    },
    events: [
      {
        type: 'social.vulnerability.updated.v1',
        summary: 'A cohort vulnerability index moved.',
        fields: {
          cohortId: 'string',
          governorate: 'gov',
          vulnerabilityIndex: 'unit',
          drivers: 'string[]',
          size: 'int',
          updatedAt: 'date',
        },
      },
      {
        type: 'social.benefit.granted.v1',
        summary: 'A benefit was granted to a cohort.',
        fields: {
          benefitId: 'string',
          cohortId: 'string',
          benefitType: 'string',
          governorate: 'gov',
          beneficiaries: 'int',
          grantedAt: 'date',
        },
      },
      {
        type: 'social.household-need.detected.v1',
        summary: 'A need was detected from cross-ministry signals before anyone asked.',
        fields: {
          needId: 'string',
          cohortId: 'string',
          needType: 'enum:water|energy|food|health|housing|schooling|income',
          governorate: 'gov',
          urgency: 'enum:normal|high|critical',
          detectedAt: 'date',
        },
      },
    ],
    apis: [
      { archetype: 'health' },
      { archetype: 'list', module: 'social-digital-twin' },
      { archetype: 'get', module: 'social-digital-twin' },
      {
        archetype: 'ai',
        method: 'POST',
        path: '/eligibility',
        module: 'zero-form-social-services',
        summary: 'Decide eligibility from signals already held, and explain the decision.',
        input: { cohortId: 'string', benefitType: 'string' },
        output: {
          needId: 'string',
          cohortId: 'string',
          needType: 'enum:water|energy|food|health|housing|schooling|income',
          governorate: 'gov',
          urgency: 'enum:normal|high|critical',
          detectedAt: 'date',
        },
        publishes: 'social.household-need.detected.v1',
      },
      {
        archetype: 'analytics',
        method: 'GET',
        path: '/vulnerability',
        module: 'social-mobility-ai',
        summary: 'Vulnerability by governorate.',
        groupBy: 'governorate',
        publishes: 'social.vulnerability.updated.v1',
      },
      { archetype: 'signals' },
      { archetype: 'twins' },
    ],
    ai: ['need detection from weak signals', 'eligibility explanation', 'mobility driver ranking'],
    iot: ['housing conditions', 'water and energy access'],
    twin: ['household cohort twin', 'governorate social twin'],
  },

  // 8 ------------------------------------------------------------------
  {
    id: 'industrial-energy',
    name: 'Industrial & Energy Intelligence Grid',
    ministry: 'Industry & Energy',
    summary: 'Production, grid load and the waste of one plant becoming the input of another.',
    mission:
      'Run industry and energy as one system: the grid knows what industry is about to do, and industry knows what the grid can afford.',
    modules: [
      {
        id: 'industrial-digital-twin-network',
        name: 'Industrial Digital Twin Network',
        purpose: 'Twin per industrial asset: output, consumption, condition.',
      },
      {
        id: 'energy-internet',
        name: 'Energy Internet',
        purpose: 'Node-level load, generation and renewable share.',
      },
      {
        id: 'ai-industrial-symbiosis',
        name: 'AI Industrial Symbiosis',
        purpose: 'Matches one plant output stream to another plant input.',
      },
    ],
    owns: ['IndustrialAssetRef', 'EnergyNodeRef', 'SymbiosisMatchRef'],
    entity: {
      collection: 'assets',
      label: 'Industrial asset',
      fields: {
        sector: 'enum:cement|textile|chemicals|agrifood|mechanical|electronics|phosphate|energy',
        governorate: 'gov',
        location: 'geo',
        outputTonnesDay: 'number',
        energyLoadMw: 'number',
        renewableShare: 'unit',
        wasteStream: 'string',
        condition: 'unit',
      },
      seed: 34,
      twin: {
        type: 'asset',
        labelField: 'sector',
        stateFields: ['energyLoadMw', 'condition', 'renewableShare'],
      },
    },
    events: [
      {
        type: 'energy.grid-load.updated.v1',
        summary: 'Load, generation and renewable share at a grid node.',
        fields: {
          nodeId: 'string',
          governorate: 'gov',
          loadMw: 'number',
          generationMw: 'number',
          renewableShare: 'unit',
          observedAt: 'date',
        },
      },
      {
        type: 'energy.outage-risk.flagged.v1',
        summary: 'A node is at risk of failing to serve its load.',
        fields: {
          nodeId: 'string',
          governorate: 'gov',
          riskScore: 'unit',
          expectedShortfallMw: 'number',
          horizonHours: 'int',
          flaggedAt: 'date',
        },
      },
      {
        type: 'industry.production.updated.v1',
        summary: 'Production changed at an industrial asset.',
        fields: {
          assetId: 'string',
          sector: 'string',
          governorate: 'gov',
          outputTonnesDay: 'number',
          energyLoadMw: 'number',
          updatedAt: 'date',
        },
      },
      {
        type: 'industry.symbiosis.matched.v1',
        summary: 'One plant waste stream was matched to another plant input.',
        fields: {
          matchId: 'string',
          sourceAssetId: 'string',
          targetAssetId: 'string',
          stream: 'string',
          tonnesPerYear: 'number',
          governorate: 'gov',
          matchedAt: 'date',
        },
      },
    ],
    apis: [
      { archetype: 'health' },
      { archetype: 'list', module: 'industrial-digital-twin-network' },
      { archetype: 'get', module: 'industrial-digital-twin-network' },
      {
        archetype: 'create',
        module: 'industrial-digital-twin-network',
        publishes: 'industry.production.updated.v1',
      },
      {
        archetype: 'ai',
        method: 'POST',
        path: '/symbiosis/match',
        module: 'ai-industrial-symbiosis',
        summary: 'Find a use for a waste stream in another plant.',
        input: { assetId: 'string', stream: 'string?' },
        output: {
          matchId: 'string',
          sourceAssetId: 'string',
          targetAssetId: 'string',
          stream: 'string',
          tonnesPerYear: 'number',
          governorate: 'gov',
          matchedAt: 'date',
        },
        publishes: 'industry.symbiosis.matched.v1',
      },
      {
        archetype: 'analytics',
        method: 'GET',
        path: '/grid/load',
        module: 'energy-internet',
        summary: 'Load and renewable share by governorate.',
        groupBy: 'governorate',
        publishes: 'energy.grid-load.updated.v1',
      },
      { archetype: 'signals' },
      { archetype: 'twins' },
    ],
    ai: ['load forecasting', 'symbiosis matching', 'equipment anomaly detection'],
    iot: ['energy load', 'vibration', 'temperature', 'air quality'],
    twin: ['industrial asset twin', 'grid node twin'],
  },

  // 9 ------------------------------------------------------------------
  {
    id: 'smart-trade',
    name: 'Smart Trade Network',
    ministry: 'Commerce & Export',
    summary: 'Product passports, export guidance and a supply graph that shows where it will break.',
    mission:
      'Give every exported product a verifiable identity, and give the country a map of the dependencies that decide whether it can be produced at all.',
    modules: [
      {
        id: 'smart-product-passport',
        name: 'Smart Product Passport',
        purpose: 'Origin, footprint and certification as a portable record.',
      },
      {
        id: 'ai-export-copilot',
        name: 'AI Export Copilot',
        purpose: 'What a producer must do to reach a target market.',
      },
      {
        id: 'national-supply-graph',
        name: 'National Supply Graph',
        purpose: 'Dependencies between products, inputs and corridors.',
      },
    ],
    owns: ['ProductRef', 'ProductPassportRef', 'ShipmentRef'],
    entity: {
      collection: 'products',
      label: 'Product',
      fields: {
        category:
          'enum:olive-oil|dates|textile|phosphate|seafood|electronics|automotive-parts|handicraft|pharma',
        hsCode: 'string',
        originGovernorate: 'gov',
        annualTonnes: 'number',
        exportShare: 'unit',
        carbonKgPerTonne: 'number',
        certified: 'bool',
      },
      seed: 30,
      twin: { type: 'process', labelField: 'category', stateFields: ['exportShare', 'certified'] },
    },
    events: [
      {
        type: 'trade.product-passport.issued.v1',
        summary: 'A product passport was issued — origin, footprint, certification.',
        fields: {
          passportId: 'string',
          productId: 'string',
          category: 'string',
          originGovernorate: 'gov',
          carbonKgPerTonne: 'number',
          issuedAt: 'date',
        },
      },
      {
        type: 'trade.shipment.updated.v1',
        summary: 'A shipment changed state.',
        fields: {
          shipmentId: 'string',
          productId: 'string',
          originGovernorate: 'gov',
          destinationCountry: 'string',
          tonnes: 'number',
          status: 'enum:booked|in-transit|customs|delivered|blocked',
          updatedAt: 'date',
        },
      },
      {
        type: 'trade.export-opportunity.detected.v1',
        summary: 'A market opening was detected for a product.',
        fields: {
          opportunityId: 'string',
          productId: 'string',
          market: 'string',
          estimatedValueTnd: 'number',
          requirements: 'string[]',
          detectedAt: 'date',
        },
      },
      {
        type: 'trade.supply-risk.flagged.v1',
        summary: 'A dependency in the supply graph is at risk.',
        fields: {
          riskId: 'string',
          productId: 'string',
          dependency: 'string',
          cause: 'string',
          severity: 'enum:low|medium|high',
          governorate: 'gov',
          flaggedAt: 'date',
        },
      },
    ],
    apis: [
      { archetype: 'health' },
      { archetype: 'list', module: 'smart-product-passport' },
      { archetype: 'get', module: 'smart-product-passport' },
      {
        archetype: 'create',
        module: 'smart-product-passport',
        publishes: 'trade.product-passport.issued.v1',
      },
      {
        archetype: 'ai',
        method: 'POST',
        path: '/export/advice',
        module: 'ai-export-copilot',
        summary: 'What this product needs to enter a given market.',
        input: { productId: 'string', market: 'string' },
        output: {
          opportunityId: 'string',
          productId: 'string',
          market: 'string',
          estimatedValueTnd: 'number',
          requirements: 'string[]',
          detectedAt: 'date',
        },
        publishes: 'trade.export-opportunity.detected.v1',
      },
      {
        archetype: 'analytics',
        method: 'GET',
        path: '/supply/graph',
        module: 'national-supply-graph',
        summary: 'Export concentration by governorate of origin.',
        groupBy: 'originGovernorate',
      },
      { archetype: 'signals' },
      { archetype: 'twins' },
    ],
    ai: ['market requirement extraction', 'supply risk propagation', 'footprint estimation'],
    iot: ['cold chain temperature', 'container GPS', 'port occupancy'],
    twin: ['product twin', 'corridor twin'],
  },

  // 10 -----------------------------------------------------------------
  {
    id: 'food-water',
    name: 'Autonomous Food & Water Grid',
    ministry: 'Agriculture & Water Resources',
    summary: 'Water where it is needed, farms that know their own state, fisheries that are not guessed at.',
    mission:
      'Turn water from a resource that is discovered to be missing into a resource that is forecast — and make that forecast reach the ministries whose plans depend on it.',
    modules: [
      {
        id: 'autonomous-water-grid',
        name: 'Autonomous Water Grid',
        purpose: 'Reservoirs, networks and demand as one balance.',
      },
      {
        id: 'ai-farm-digital-twin',
        name: 'AI Farm Digital Twin',
        purpose: 'Soil, crop and irrigation state per farm.',
      },
      {
        id: 'smart-ocean-fisheries-network',
        name: 'Smart Ocean & Fisheries Network',
        purpose: 'Stock and effort per fishing zone.',
      },
    ],
    owns: ['FarmRef', 'WaterAssetRef', 'FishingZoneRef'],
    entity: {
      collection: 'farms',
      label: 'Farm',
      fields: {
        crop: 'enum:olive|date|cereal|citrus|vegetable|forage|vine|greenhouse',
        governorate: 'gov',
        location: 'geo',
        areaHectares: 'number',
        soilMoisturePct: 'number',
        irrigationType: 'enum:drip|sprinkler|flood|rainfed',
        waterDemandM3Day: 'number',
        yieldForecastTonnes: 'number',
        stressIndex: 'unit',
      },
      seed: 44,
      twin: {
        type: 'farm',
        labelField: 'crop',
        stateFields: ['soilMoisturePct', 'stressIndex', 'waterDemandM3Day'],
      },
    },
    events: [
      {
        type: 'agriculture.water-demand.predicted.v1',
        summary: 'Forecast water demand for a zone — the canonical cross-ministry forecast on this platform.',
        fields: {
          forecastId: 'string',
          governorate: 'gov',
          horizonDays: 'int',
          demandM3Day: 'number',
          confidence: 'unit',
          drivers: 'string[]',
          predictedAt: 'date',
        },
      },
      {
        type: 'agriculture.water-shortage.predicted.v1',
        summary: 'A shortage is expected: demand will exceed available supply.',
        fields: {
          alertId: 'string',
          governorate: 'gov',
          horizonDays: 'int',
          deficitM3Day: 'number',
          severity: 'enum:watch|alert|critical',
          affectedFarms: 'int',
          predictedAt: 'date',
        },
      },
      {
        type: 'agriculture.yield.forecast.v1',
        summary: 'Expected yield for a crop in a governorate.',
        fields: {
          forecastId: 'string',
          crop: 'string',
          governorate: 'gov',
          expectedTonnes: 'number',
          varianceFromBaseline: 'number',
          predictedAt: 'date',
        },
      },
      {
        type: 'water.reservoir-level.updated.v1',
        summary: 'Reservoir fill level changed.',
        fields: {
          assetId: 'string',
          governorate: 'gov',
          fillPct: 'unit',
          volumeM3: 'number',
          trend: 'enum:rising|stable|falling',
          observedAt: 'date',
        },
      },
      {
        type: 'fisheries.stock.updated.v1',
        summary: 'Stock and fishing effort for a maritime zone.',
        fields: {
          zoneId: 'string',
          species: 'string',
          stockIndex: 'unit',
          effortBoats: 'int',
          observedAt: 'date',
        },
      },
    ],
    apis: [
      { archetype: 'health' },
      { archetype: 'list', module: 'ai-farm-digital-twin' },
      { archetype: 'get', module: 'ai-farm-digital-twin' },
      { archetype: 'create', module: 'ai-farm-digital-twin' },
      {
        archetype: 'ai',
        method: 'POST',
        path: '/water/demand/forecast',
        module: 'autonomous-water-grid',
        summary: 'Forecast water demand for a governorate from soil, weather and crop state.',
        input: { governorate: 'gov', horizonDays: 'int?' },
        output: {
          forecastId: 'string',
          governorate: 'gov',
          horizonDays: 'int',
          demandM3Day: 'number',
          confidence: 'unit',
          drivers: 'string[]',
          predictedAt: 'date',
        },
        publishes: 'agriculture.water-demand.predicted.v1',
      },
      {
        archetype: 'ai',
        method: 'POST',
        path: '/water/shortage/predict',
        module: 'autonomous-water-grid',
        summary: 'Predict a shortage and alert every ministry that depends on water.',
        input: { governorate: 'gov', horizonDays: 'int?' },
        output: {
          alertId: 'string',
          governorate: 'gov',
          horizonDays: 'int',
          deficitM3Day: 'number',
          severity: 'enum:watch|alert|critical',
          affectedFarms: 'int',
          predictedAt: 'date',
        },
        publishes: 'agriculture.water-shortage.predicted.v1',
      },
      {
        archetype: 'analytics',
        method: 'GET',
        path: '/irrigation/plan',
        module: 'autonomous-water-grid',
        summary: 'Water demand by governorate.',
        groupBy: 'governorate',
      },
      { archetype: 'signals' },
      { archetype: 'twins' },
    ],
    ai: ['water demand forecasting', 'shortage prediction', 'yield forecasting', 'irrigation optimisation'],
    iot: ['soil moisture', 'water level', 'rainfall', 'temperature', 'humidity'],
    twin: ['farm twin', 'reservoir twin', 'fishing zone twin'],
  },

  // 11 -----------------------------------------------------------------
  {
    id: 'skills-opportunity',
    name: 'National Skills & Opportunity OS',
    ministry: 'Employment & Vocational Training',
    summary: 'What the country can do, what it needs to be able to do, and the shortest path between.',
    mission:
      'Read skill demand from what the other ministries are actually building, and open real missions against the gaps.',
    modules: [
      {
        id: 'national-skills-graph',
        name: 'National Skills Graph',
        purpose: 'Skills, adjacencies and regional supply.',
      },
      {
        id: 'ai-career-digital-twin',
        name: 'AI Career Digital Twin',
        purpose: 'A path from where a person is to where demand is.',
      },
      {
        id: 'national-micro-mission-network',
        name: 'National Micro-Mission Network',
        purpose: 'Short, real assignments published against detected gaps.',
      },
    ],
    owns: ['SkillRef', 'MicroMissionRef', 'CareerPathRef'],
    entity: {
      collection: 'skills',
      label: 'Skill',
      fields: {
        domain:
          'enum:water|energy|health|digital|logistics|agriculture|construction|tourism|education|finance',
        governorate: 'gov',
        supplyIndex: 'unit',
        demandIndex: 'unit',
        gap: 'number',
        trainingMonths: 'int',
        adjacentSkills: 'string[]',
      },
      seed: 40,
      twin: { type: 'process', labelField: 'domain', stateFields: ['gap', 'demandIndex'] },
    },
    events: [
      {
        type: 'skills.gap.detected.v1',
        summary: 'Demand for a skill exceeds regional supply.',
        fields: {
          gapId: 'string',
          skill: 'string',
          domain: 'string',
          governorate: 'gov',
          gap: 'number',
          drivenBy: 'string[]',
          detectedAt: 'date',
        },
      },
      {
        type: 'skills.micro-mission.published.v1',
        summary: 'A short real assignment was opened against a gap.',
        fields: {
          missionId: 'string',
          title: 'string',
          skill: 'string',
          governorate: 'gov',
          durationDays: 'int',
          requestedBy: 'string',
          publishedAt: 'date',
        },
      },
      {
        type: 'skills.profile.updated.v1',
        summary: 'Regional skill supply moved.',
        fields: {
          skill: 'string',
          governorate: 'gov',
          supplyIndex: 'unit',
          demandIndex: 'unit',
          updatedAt: 'date',
        },
      },
    ],
    apis: [
      { archetype: 'health' },
      { archetype: 'list', module: 'national-skills-graph' },
      { archetype: 'get', module: 'national-skills-graph' },
      {
        archetype: 'create',
        module: 'national-micro-mission-network',
        publishes: 'skills.micro-mission.published.v1',
      },
      {
        archetype: 'ai',
        method: 'POST',
        path: '/career/plan',
        module: 'ai-career-digital-twin',
        summary: 'Build a training path from a current profile to real regional demand.',
        input: { currentSkills: 'string[]', governorate: 'gov', targetDomain: 'string?' },
        output: {
          gapId: 'string',
          skill: 'string',
          domain: 'string',
          governorate: 'gov',
          gap: 'number',
          drivenBy: 'string[]',
          detectedAt: 'date',
        },
        publishes: 'skills.gap.detected.v1',
      },
      {
        archetype: 'analytics',
        method: 'GET',
        path: '/gaps',
        module: 'national-skills-graph',
        summary: 'Skill gaps by governorate.',
        groupBy: 'governorate',
      },
      { archetype: 'signals' },
      { archetype: 'twins' },
    ],
    ai: ['gap detection from cross-ministry demand', 'career path planning', 'skill adjacency embedding'],
    iot: ['training centre occupancy'],
    twin: ['skill twin', 'regional labour twin'],
  },

  // 12 -----------------------------------------------------------------
  {
    id: 'health',
    name: 'Connected Health Intelligence System',
    ministry: 'Health',
    summary: 'Hospital capacity, epidemic signals and care that reaches beyond the hospital walls.',
    mission:
      'Publish capacity continuously so no other ministry has to guess it, and read the environment so that a health event is anticipated rather than counted.',
    modules: [
      {
        id: 'personal-health-digital-twin',
        name: 'Personal Health Digital Twin',
        purpose: 'Pseudonymous cohort twins — never an identified person.',
      },
      {
        id: 'smart-hospital-operating-system',
        name: 'Smart Hospital Operating System',
        purpose: 'Beds, ICU, emergency load, in real time.',
      },
      {
        id: 'healthcare-mesh',
        name: 'Healthcare Mesh',
        purpose: 'Coordination with transport, social services and emergency.',
      },
    ],
    owns: ['HospitalRef', 'HealthCapacity', 'CareEpisodeRef'],
    entity: {
      collection: 'facilities',
      label: 'Health facility',
      fields: {
        facilityType: 'enum:regional-hospital|university-hospital|health-centre|clinic|dispensary',
        governorate: 'gov',
        location: 'geo',
        totalBeds: 'int',
        availableBeds: 'int',
        icuAvailable: 'int',
        emergencyLoad: 'unit',
        specialties: 'string[]',
      },
      seed: 34,
      twin: {
        type: 'hospital',
        labelField: 'facilityType',
        stateFields: ['availableBeds', 'emergencyLoad', 'icuAvailable'],
      },
    },
    events: [
      {
        type: 'health.capacity.updated.v1',
        summary: 'Bed and emergency capacity at a facility. Consumed widely — dispatch depends on it.',
        fields: {
          facilityId: 'string',
          governorate: 'gov',
          location: 'geo',
          totalBeds: 'int',
          availableBeds: 'int',
          icuAvailable: 'int',
          emergencyLoad: 'unit',
          observedAt: 'date',
        },
      },
      {
        type: 'health.epidemic-signal.detected.v1',
        summary: 'An unusual health signal was detected in a governorate.',
        fields: {
          signalId: 'string',
          governorate: 'gov',
          syndrome: 'string',
          excessCases: 'int',
          confidence: 'unit',
          suspectedDrivers: 'string[]',
          detectedAt: 'date',
        },
      },
      {
        type: 'health.emergency.declared.v1',
        summary: 'Health declares an emergency requiring resources it does not own.',
        fields: {
          emergencyId: 'string',
          governorate: 'gov',
          location: 'geo',
          requiredResources: 'string[]',
          patients: 'int',
          declaredAt: 'date',
        },
      },
      {
        type: 'health.care-episode.updated.v1',
        summary: 'Aggregate care activity for a cohort.',
        fields: {
          cohortId: 'string',
          governorate: 'gov',
          episodes: 'int',
          averageStayDays: 'number',
          updatedAt: 'date',
        },
      },
    ],
    apis: [
      { archetype: 'health' },
      { archetype: 'list', module: 'smart-hospital-operating-system' },
      { archetype: 'get', module: 'smart-hospital-operating-system' },
      {
        archetype: 'analytics',
        method: 'GET',
        path: '/capacity',
        module: 'smart-hospital-operating-system',
        summary: 'Capacity by governorate. The endpoint every dispatcher calls.',
        groupBy: 'governorate',
        publishes: 'health.capacity.updated.v1',
      },
      {
        archetype: 'ai',
        method: 'POST',
        path: '/triage',
        module: 'healthcare-mesh',
        summary: 'Assess a case description and name the facility type it needs.',
        input: { description: 'text', governorate: 'gov?' },
        output: {
          urgency: 'enum:routine|urgent|emergency|critical',
          suspectedCategory: 'string',
          recommendedFacility: 'string',
          reasoning: 'text',
          confidence: 'unit',
        },
      },
      {
        archetype: 'ai',
        method: 'POST',
        path: '/epidemic/scan',
        module: 'personal-health-digital-twin',
        summary: 'Scan cohort and environmental signals for an emerging epidemic pattern.',
        input: { governorate: 'gov' },
        output: {
          signalId: 'string',
          governorate: 'gov',
          syndrome: 'string',
          excessCases: 'int',
          confidence: 'unit',
          suspectedDrivers: 'string[]',
          detectedAt: 'date',
        },
        publishes: 'health.epidemic-signal.detected.v1',
      },
      { archetype: 'signals' },
      { archetype: 'twins' },
    ],
    ai: ['triage', 'epidemic signal detection', 'capacity forecasting'],
    iot: ['wearable heart rate', 'air quality', 'occupancy', 'temperature'],
    twin: ['hospital twin', 'cohort health twin'],
  },
];
