export * from './registry.ts';
export * from './api.ts';

/**
 * Importing this module registers EVERY event contract on the platform.
 * The barrel below is generated by `pnpm generate` from tools/spec/services.mjs.
 */
export * from './events/index.ts';
