/**
 * SERVICE REGISTRY — how the platform finds the 24 ministries.
 *
 * Generated by `pnpm generate`. Dynamic imports, so `pnpm dev:service health`
 * can load one ministry without paying for the other 23.
 */
import type { ServiceDefinition } from '@platform/service-kit';

export const SERVICE_MODULES: Record<string, () => Promise<{ default: ServiceDefinition }>> = {
  justice: () => import('./justice/src/index.ts'),
  resilience: () => import('./resilience/src/index.ts'),
  'safety-emergency': () => import('./safety-emergency/src/index.ts'),
  'global-tunisia': () => import('./global-tunisia/src/index.ts'),
  treasury: () => import('./treasury/src/index.ts'),
  'national-digital-twin': () => import('./national-digital-twin/src/index.ts'),
  'social-mobility': () => import('./social-mobility/src/index.ts'),
  'industrial-energy': () => import('./industrial-energy/src/index.ts'),
  'smart-trade': () => import('./smart-trade/src/index.ts'),
  'food-water': () => import('./food-water/src/index.ts'),
  'skills-opportunity': () => import('./skills-opportunity/src/index.ts'),
  health: () => import('./health/src/index.ts'),
  education: () => import('./education/src/index.ts'),
  research: () => import('./research/src/index.ts'),
  talent: () => import('./talent/src/index.ts'),
  'religious-heritage': () => import('./religious-heritage/src/index.ts'),
  'digital-nervous-system': () => import('./digital-nervous-system/src/index.ts'),
  'mobility-logistics': () => import('./mobility-logistics/src/index.ts'),
  infrastructure: () => import('./infrastructure/src/index.ts'),
  land: () => import('./land/src/index.ts'),
  environment: () => import('./environment/src/index.ts'),
  tourism: () => import('./tourism/src/index.ts'),
  'life-care': () => import('./life-care/src/index.ts'),
  culture: () => import('./culture/src/index.ts'),
};

export const SERVICE_IDS = Object.keys(SERVICE_MODULES);

export async function loadService(id: string): Promise<ServiceDefinition> {
  const loader = SERVICE_MODULES[id];
  if (!loader) {
    throw new Error(`Unknown service "${id}". The 24 ids are: ${SERVICE_IDS.join(', ')}`);
  }
  return (await loader()).default;
}

export async function loadAllServices(): Promise<ServiceDefinition[]> {
  return Promise.all(SERVICE_IDS.map((id) => loadService(id)));
}
