/**
 * Importing this barrel registers all 84 event contracts.
 * Generated by `pnpm generate`.
 */
export * from '../services.ts';
export * from './justice.ts';
export * from './resilience.ts';
export * from './safety-emergency.ts';
export * from './global-tunisia.ts';
export * from './treasury.ts';
export * from './national-digital-twin.ts';
export * from './social-mobility.ts';
export * from './industrial-energy.ts';
export * from './smart-trade.ts';
export * from './food-water.ts';
export * from './skills-opportunity.ts';
export * from './health.ts';
export * from './education.ts';
export * from './research.ts';
export * from './talent.ts';
export * from './religious-heritage.ts';
export * from './digital-nervous-system.ts';
export * from './mobility-logistics.ts';
export * from './infrastructure.ts';
export * from './land.ts';
export * from './environment.ts';
export * from './tourism.ts';
export * from './life-care.ts';
export * from './culture.ts';
